import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_stripe/flutter_stripe.dart';
import 'package:get/get.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:scouttalent2/utils/app_translation.dart';
import 'package:scouttalent2/utils/subscriptionFlow.dart';
import 'service/notification_service.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

import 'backend/helper/app_router.dart';
import 'backend/helper/init.dart';
import 'utils/connectivity.dart';
import 'utils/string.dart';
import 'utils/theme.dart';
import 'view/noConnectivityScreen.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:sizer/sizer.dart';



BuildContext getContext = Get.key.currentContext!;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await MainBinding().dependencies();
  String locale = await getSavedLocale();
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);


  await checkAndRequestNotificationPermission();
  await NotificationHandler().initialize(Get.key);
  setupFCMToken();
/*
  String? token = await FirebaseMessaging.instance.getToken();
  if (token != null) {
    print("FCM Token: $token");

    SharedPreferences prefs = await SharedPreferences.getInstance();
    await prefs.setString(AppString.fcmToken, token);

    String? savedToken = prefs.getString(AppString.fcmToken);
    print("Saved FCM Token: $savedToken");
  }
*/


  _stripeSetup();
  Get.put(ConnectivityController());
  Get.put(AppStateController(), permanent: true);
  runApp(MyApp(locale: locale));
  //setupFCMToken();
}


Future<void> setupFCMToken({int retryCount = 0}) async {
  const int maxRetries = 5;
  debugPrint("🚀 setupFCMToken called | retryCount=$retryCount");
  try {
    final messaging = FirebaseMessaging.instance;

    // iOS safety (keep your logic)
    if (GetPlatform.isIOS) {
      String? apnsToken;
      int apnsRetry = 0;
      while (apnsToken == null && apnsRetry < 5) {
        debugPrint("🍎 Waiting for APNS token (attempt $apnsRetry)");
        apnsToken = await messaging.getAPNSToken();
        await Future.delayed(const Duration(milliseconds: 300));
        apnsRetry++;
      }
      debugPrint("🍎 APNS token received: $apnsToken");
    }

    final token = await messaging.getToken();

    if (token != null) {
      debugPrint("✅ FCM Token: $token");

      SharedPreferences prefs = await SharedPreferences.getInstance();
      await prefs.setString(AppString.fcmToken, token);
      debugPrint("💾 FCM Token saved locally");
      return; // success, stop retrying
    }

    throw Exception("Token is null");
  } catch (e) {
    debugPrint("❌ FCM Token error (retry $retryCount): $e");

    if (retryCount < maxRetries) {
      await Future.delayed(const Duration(seconds: 3));
      await setupFCMToken(retryCount: retryCount + 1);
    } else {
      debugPrint("⚠️ FCM token retry limit reached");
    }
  }

  // Token refresh listener (keep this)
  FirebaseMessaging.instance.onTokenRefresh.listen((token) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    await prefs.setString(AppString.fcmToken, token);
    debugPrint("🔁 FCM Token refreshed: $token");
  });
}


Future<void> checkAndRequestNotificationPermission() async {
  final prefs = await SharedPreferences.getInstance();

  final status = await Permission.notification.status;

  if (status.isGranted) {
    // Already allowed
    await prefs.setBool('notifications_enabled', true);
    return;
  }

  if (status.isDenied) {
    // First time OR denied once → request
    final result = await Permission.notification.request();

    final enabled = result.isGranted;
    await prefs.setBool('notifications_enabled', enabled);

    debugPrint("Notification permission result: $enabled");
    return;
  }

  if (status.isPermanentlyDenied) {
    // User blocked it manually
    await prefs.setBool('notifications_enabled', false);
    debugPrint("Notification permanently denied. Open settings.");
    // Optional:
    // openAppSettings();
  }
}


Future<void> _requestNotificationPermission() async {
  NotificationSettings settings = await FirebaseMessaging.instance
      .requestPermission(alert: true, badge: true, sound: true);

  if (settings.authorizationStatus == AuthorizationStatus.authorized) {
    print('User granted permission');
  } else {
    print('User declined or has not accepted permission');
  }
}

Future<void> _stripeSetup() async {
  await dotenv.load(fileName: "assets/.env");
  Stripe.publishableKey = dotenv.env['STRIPE_PUBLISH_KEY']!;
  await Stripe.instance.applySettings();
}

class MyApp extends StatelessWidget {
  final String locale;

  const MyApp({super.key, required this.locale});

  @override
  Widget build(BuildContext context) {
    print("THE LOCALE>>$locale");
    return Sizer(
      builder: (context, orientation, deviceType) {
        SystemChrome.setSystemUIOverlayStyle(
          SystemUiOverlayStyle(statusBarColor: ThemeProvider.primary),
        );
        return GetMaterialApp(
          title: 'Scouttalent',
          debugShowCheckedModeBanner: false,
          navigatorKey: Get.key,
          translations: AppTranslation(),

          initialRoute: AppRouter.splash,
          getPages: AppRouter.routes,
          defaultTransition: Transition.fadeIn,
          locale: Locale(locale),
          fallbackLocale: const Locale('en'),
          builder: (context, child) {
            return Obx(() {
              final controller = Get.find<ConnectivityController>();
              return Stack(
                children: [
                  child ?? const SizedBox.shrink(),
                  if (!controller.isConnected) const NoConnectivityScreen(),
                ],
              );
            });
          },
        );
      },
    );
  }
}

Future<String> getSavedLocale() async {
  SharedPreferences prefs = await SharedPreferences.getInstance();
  String? langCode = prefs.getString(AppString.currentLang);
  return langCode ?? 'en';
}
